name: chat_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-334.3.beta

dependencies:
  aligned_dialog: ^0.0.7
  animated_splash_screen: ^1.3.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_supabase_chat_core: ^1.4.2
  flutter_svg: ^2.0.16
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.3
  quickalert: ^1.1.0
  supabase_flutter: ^2.8.2
  flutter_screenutil:

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/vectors/
  fonts:
    - family: Axiforma
      fonts:
        - asset: assets/fonts/Axiforma-Black.ttf
          weight: 800
        - asset: assets/fonts/Axiforma-Bold.ttf
          weight: 700
        - asset: assets/fonts/Axiforma-Medium.ttf
          weight: 500
        - asset: assets/fonts/Axiforma-Regular.ttf
          weight: 400